# Some text processing functions in sklearn
## CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer()
corpus = ['This is the first document.',
          'This is the second second document.',
          'And the third one.',
          'Is this the first document?']
X = vectorizer.fit_transform(corpus)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [3]:
vectorizer.get_feature_names()

/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [4]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [5]:
vectorizer.transform(['Something completely new.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
vectorizer.transform(['A document with repeated document word']).toarray()

array([[0, 2, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
cosine_similarity(X)

array([[1.        , 0.63245553, 0.2236068 , 1.        ],
       [0.63245553, 1.        , 0.1767767 , 0.63245553],
       [0.2236068 , 0.1767767 , 1.        , 0.2236068 ],
       [1.        , 0.63245553, 0.2236068 , 1.        ]])

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(corpus)
X_tfidf

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [10]:
X_tfidf.toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

In [11]:
cosine_similarity(X_tfidf)

array([[1.        , 0.43830038, 0.1034849 , 1.        ],
       [0.43830038, 1.        , 0.06422193, 0.43830038],
       [0.1034849 , 0.06422193, 1.        , 0.1034849 ],
       [1.        , 0.43830038, 0.1034849 , 1.        ]])

## HashingVectorizer

In [12]:
from sklearn.feature_extraction.text import HashingVectorizer
hv = HashingVectorizer(n_features=5)
hv.transform(corpus).toarray()

array([[ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ],
       [ 0.81649658,  0.        ,  0.40824829, -0.40824829,  0.        ],
       [-0.5       ,  0.5       ,  0.        , -0.5       , -0.5       ],
       [ 0.        , -0.57735027,  0.57735027, -0.57735027,  0.        ]])

In [13]:
cosine_similarity(hv.transform(corpus))

array([[ 1.        ,  0.47140452,  0.        ,  1.        ],
       [ 0.47140452,  1.        , -0.20412415,  0.47140452],
       [ 0.        , -0.20412415,  1.        ,  0.        ],
       [ 1.        ,  0.47140452,  0.        ,  1.        ]])

# An Example of Text Clustering
Let's use the tweet data set from assignment 2 ... because we can.

In [14]:
import pandas as pd
tweets_pd = pd.read_json("10000 tweets_clean.zip")
tweets_pd.head()

id objectType                                              actor  \
0  1.497157e+20   activity  {'objectType': 'person', 'id': '10243188921458...   
1  1.497157e+20   activity  {'objectType': 'person', 'id': '1024397578801'...   
2  1.497157e+20   activity  {'objectType': 'person', 'id': '10243126525057...   
3  1.497157e+20   activity  {'objectType': 'person', 'id': '10243295689843...   
4  1.497157e+20   activity  {'objectType': 'person', 'id': '1024318064228'...   

   verb                postedTime  \
0  post  2016-04-01T00:00:01.000Z   
1  post  2016-04-01T00:00:01.000Z   
2  post  2016-04-01T00:00:01.000Z   
3  post  2016-04-01T00:00:03.000Z   
4  post  2016-04-01T00:00:00.000Z   

                                           generator  \
0  {'displayName': 'Facebook', 'link': 'http://ww...   
1  {'displayName': 'Weather Display Tweet', 'link...   
2  {'displayName': 'Sprinklr', 'link': 'http://ww...   
3  {'displayName': 'Facebook', 'link': 'http://ww...   
4  {'displayName': 'HubSpot', 'link': 'http://www...   

                                            provider  \
0  {'objectType': 'service', 'displayName': 'Twit...   
1  {'objectType': 'service', 'displayName': 'Twit...   
2  {'objectType': 'service', 'displayName': 'Twit...   
3  {'objectType': 'service', 'displayName': 'Twit...   
4  {'objectType': 'service', 'displayName': 'Twit...   

                                                link  \
0  http://twitter.com/losebabyweight1/statuses/71...   
1  http://twitter.com/wantirnaweather/statuses/71...   
2  http://twitter.com/sas_anz/statuses/7156901408...   
3  http://twitter.com/Letticlothing/statuses/7156...   
4  http://twitter.com/Intelledox/statuses/7156901...   

                                                text  \
0  CONGRATULATIONS Suzie Walker on both your beau...   
1  Wantirna, VIC, AU 11:00 AM Temp 19.8°C, RH 67p...   
2  Join us @ the Hilton Sydney 2 learn how 2 make...   
3  Say Hello to this Gorgeous Gingham Dress! \n\n...   
4  Register for #Convergence2016 to hear@ChelleMe...   

                                              object  ...  \
0  {'objectType': 'note', 'id': '1345715690143449...  ...   
1  {'objectType': 'note', 'id': '1345715690141306...  ...   
2  {'objectType': 'note', 'id': '1345715690140849...  ...   
3  {'objectType': 'note', 'id': '1345715690148764...  ...   
4  {'objectType': 'note', 'id': '1345715690137900...  ...   

                                    twitter_entities twitter_filter_level  \
0  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
1  {'hashtags': [{'text': 'vicweather', 'indices'...                  low   
2  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
3  {'hashtags': [], 'urls': [{'url': 'https://t.c...                  low   
4  {'hashtags': [{'text': 'Convergence2016', 'ind...                  low   

  twitter_lang retweetCount  \
0           en            0   
1           en            0   
2           en            0   
3           en            0   
4           en            0   

                                                gnip  \
0  {'matching_rules': [{'value': 'bio_location: "...   
1  {'matching_rules': [{'value': 'bio_location: "...   
2  {'matching_rules': [{'value': 'bio_location: "...   
3  {'matching_rules': [{'value': 'bio_location: "...   
4  {'matching_rules': [{'value': 'bio_location: "...   

                           twitter_extended_entities inReplyTo  \
0                                                NaN       NaN   
1                                                NaN       NaN   
2  {'media': [{'id': 'NumberLong(1569014044273459...       NaN   
3                                                NaN       NaN   
4                                                NaN       NaN   

  twitter_quoted_status location  geo  
0                   NaN      NaN  NaN  
1                   NaN      NaN  NaN  
2                   NaN      NaN  NaN  
3                   NaN      NaN  NaN  
4   

In [15]:
tweets_vectorizer = TfidfVectorizer()
vectors = tweets_vectorizer.fit_transform(tweets_pd.text)
vectors

<10000x31628 sparse matrix of type '<class 'numpy.float64'>'
	with 139080 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10, random_state=0).fit(vectors)

In [17]:
kmeans.predict(vectors[:5])

array([4, 1, 5, 5, 5], dtype=int32)

# Topic Modelling
Watch the videos at [https://pyldavis.readthedocs.io/en/latest/readme.html](https://pyldavis.readthedocs.io/en/latest/readme.html) for examples of the use of pyLDAvis

In [18]:
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis
import pyLDAvis.sklearn

In [19]:
lda_model = LatentDirichletAllocation(n_components=20, # Number of topics
                                      learning_method='online', # Faster when using large volumes of data
                                      random_state=0,       
                                      n_jobs = -1  # Use all available CPUs
                                     )

LatentDirichetAllocation needs to use count vectors. This is because of the nature of their algorithm. For further details, read this discussion: https://datascience.stackexchange.com/questions/21950/why-we-should-not-feed-lda-with-tfidf

In [20]:
count_vectorizer = CountVectorizer()
count_vectors = count_vectorizer.fit_transform(tweets_pd.text)
lda_output = lda_model.fit_transform(count_vectors)

In [21]:
pyLDAvis.enable_notebook()
pyLDAvis.sklearn.prepare(lda_model, count_vectors, count_vectorizer, mds='tsne')

/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/srv/conda/envs/notebook/lib/python3.8/site-packages/pyLDAvis/_prepare.py:246: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  default_term_info = default_term_info.sort_values(
/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py:780: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py:790: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(
/srv/conda/envs/notebook/lib/python3.8/site-packages/

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
1      -10.878068   10.538728       1        1  29.096025
4      -60.884026  -75.591820       2        1  12.030753
6       -2.336119  -53.289074       3        1   9.526384
3      -61.385319  -12.914634       4        1   9.210484
8      -28.737743  126.296997       5        1   6.001867
18       1.066606 -123.552811       6        1   3.486178
13      45.140720   -7.947869       7        1   3.320842
11    -140.795975  -98.530548       8        1   3.279369
5       61.531681  -83.240562       9        1   2.619524
2      -72.563057 -140.396881      10        1   2.515341
7       15.984491   63.578186      11        1   2.318039
0     -160.851624   68.945145      12        1   2.275639
14      85.961830   51.922935      13        1   2.005564
9      -99.020836  109.936348      14        1   1.921172
17    -176.764130   -8.681684      15        1   1.832312
12    -117.189880  -37.420200      16        1   1.794091
10     108.829918  -22.946203      17        1   1.782129
15      47.588097  121.934814      18        1   1.723776
19    -106.467834   30.176889      19        1   1.671961
16     -50.613804   59.328842      20        1   1.588548, topic_info=               Term         Freq        Total Category  logprob  loglift
12783         https  6244.000000  6244.000000  Default  30.0000  30.0000
6211             co  5723.000000  5723.000000  Default  29.0000  29.0000
26166           the  3103.000000  3103.000000  Default  28.0000  28.0000
22926            rt  3891.000000  3891.000000  Default  27.0000  27.0000
29820           you  1279.000000  1279.000000  Default  26.0000  26.0000
...             ...          ...          ...      ...      ...      ...
13740        isobar     6.707931     7.421798  Topic20  -5.8496   4.0412
21567    qnm9sfakf8     6.707924     7.421801  Topic20  -5.8496   4.0412
5931   christianity     6.703293     7.417082  Topic20  -5.8503   4.0412
29009     wisconsin     6.438590     7.152380  Topic20  -5.8906   4.0372
22926            rt    26.603526  3891.952386  Topic20  -4.4719  -0.8433

[816 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
7         11  0.927867     01
130       11  0.993476     10
173        9  0.086955     11
173       11  0.898531     11
185        1  0.663085     12
...      ...       ...    ...
31523     20  0.943170     없을
31549     20  0.943170    인간의
31595     20  0.943170  탑골공원의
31610     20  0.943170    할배를
31611     20  0.943170     해도

[932 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[2, 5, 7, 4, 9, 19, 14, 12, 6, 3, 8, 1, 15, 10, 18, 13, 11, 16, 20, 17])

Topics 1 and 2 are much larger than the rest. If you hover over them you will see that most of the words are stop words (which we have not removed). Let's remove stop words and repeat the analysis.

In [22]:
count_vectorizer_nonstop = CountVectorizer(stop_words="english")
count_vectors_nonstop = count_vectorizer_nonstop.fit_transform(tweets_pd.text)
count_vectors_nonstop

<10000x31356 sparse matrix of type '<class 'numpy.int64'>'
	with 94731 stored elements in Compressed Sparse Row format>

In [23]:
lda_model_nonstop = LatentDirichletAllocation(n_components=20, # Number of topics
                                              learning_method='online', # Faster when using large volumes of data
                                              random_state=0,       
                                              n_jobs = -1  # Use all available CPUs
                                              )

In [24]:
lda_output_nonstop = lda_model_nonstop.fit_transform(count_vectors_nonstop)

In [25]:
pyLDAvis.sklearn.prepare(lda_model_nonstop, count_vectors_nonstop, count_vectorizer_nonstop, mds='tsne')

/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/srv/conda/envs/notebook/lib/python3.8/site-packages/pyLDAvis/_prepare.py:246: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  default_term_info = default_term_info.sort_values(
/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py:780: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/manifold/_t_sne.py:790: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(
/srv/conda/envs/notebook/lib/python3.8/site-packages/

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
14     -10.878068   10.538728       1        1  13.239868
4      -60.884026  -75.591820       2        1  10.073149
6       -2.336119  -53.289074       3        1   7.234080
0      -61.385319  -12.914634       4        1   6.894884
11     -28.737743  126.296997       5        1   5.154550
12       1.066606 -123.552811       6        1   4.807425
5       45.140720   -7.947869       7        1   4.782961
18    -140.795975  -98.530548       8        1   4.672913
1       61.531681  -83.240562       9        1   4.660880
15     -72.563057 -140.396881      10        1   4.507198
8       15.984491   63.578186      11        1   4.059587
10    -160.851624   68.945145      12        1   3.807668
19      85.961830   51.922935      13        1   3.729600
2      -99.020836  109.936348      14        1   3.605322
9     -176.764130   -8.681684      15        1   3.507729
17    -117.189880  -37.420200      16        1   3.402764
13     108.829918  -22.946203      17        1   3.122482
3       47.588097  121.934814      18        1   2.956158
16    -106.467834   30.176889      19        1   2.908563
7      -50.613804   59.328842      20        1   2.872221, topic_info=         Term         Freq        Total Category  logprob  loglift
22744      rt  3475.000000  3475.000000  Default  30.0000  30.0000
12670   https  5413.000000  5413.000000  Default  29.0000  29.0000
14451    just   289.000000   289.000000  Default  28.0000  28.0000
26236  threat   242.000000   242.000000  Default  27.0000  27.0000
15805    like   234.000000   234.000000  Default  26.0000  26.0000
...       ...          ...          ...      ...      ...      ...
4123      bid     6.093868     6.796328  Topic20  -6.1333   3.4410
3062    asked     6.001523     6.703984  Topic20  -6.1486   3.4394
2785      apa     5.556687     6.259147  Topic20  -6.2256   3.4310
8692     ebay     5.386568     6.089028  Topic20  -6.2567   3.4275
185        12     9.281893    45.131728  Topic20  -5.7125   1.9686

[732 rows x 6 columns], token_table=       Topic      Freq   Term
term                         
1          7  0.980313    000
7         13  0.931844     01
19        13  0.948804     04
130        8  0.988013     10
173       13  0.993438     11
...      ...       ...    ...
31251     19  0.893697     없을
31277     19  0.893697    인간의
31323     19  0.893697  탑골공원의
31338     19  0.893697    할배를
31339     19  0.893697     해도

[752 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[15, 5, 7, 1, 12, 13, 6, 19, 2, 16, 9, 11, 20, 3, 10, 18, 14, 4, 17, 8])

The following code displays the document vectors. The resulting pandas table shows the topics and columns. Then, each row shows the distribution of topic probabilities for a document. Thus, the sum of numbers of each row should be 1.

For example, we can see that the most prominent topic of document 0 is topic 1. 84.47% of the words from document 0 would belong to topic 1.

In [26]:
lda_vectors = pd.DataFrame(lda_output_nonstop)
lda_vectors.columns = ['Topic '+str(i) for i in range(lda_vectors.shape[1])]
lda_vectors.index = ['Document '+str(i) for i in range(lda_vectors.shape[0])]
lda_vectors.head()

Topic 0   Topic 1   Topic 2   Topic 3   Topic 4   Topic 5  \
Document 0  0.003846  0.844783  0.003846  0.003846  0.003846  0.003846   
Document 1  0.002381  0.002381  0.002381  0.002381  0.002381  0.002381   
Document 2  0.003571  0.003571  0.003571  0.003571  0.003571  0.003571   
Document 3  0.003333  0.003333  0.003333  0.003333  0.003333  0.003333   
Document 4  0.004167  0.004167  0.004167  0.004167  0.004167  0.004167   

             Topic 6   Topic 7   Topic 8   Topic 9  Topic 10  Topic 11  \
Document 0  0.003846  0.003846  0.003846  0.085986  0.003846  0.003846   
Document 1  0.050000  0.002381  0.002381  0.002381  0.002381  0.050000   
Document 2  0.217857  0.003571  0.003571  0.003571  0.003571  0.003571   
Document 3  0.071851  0.003333  0.003333  0.003333  0.003333  0.003333   
Document 4  0.004167  0.004167  0.004167  0.004167  0.092793  0.004167   

            Topic 12  Topic 13  Topic 14  Topic 15  Topic 16  Topic 17  \
Document 0  0.003846  0.003846  0.003846  0.003846  0.003846  0.003846   
Document 1  0.002381  0.002381  0.002381  0.002381  0.002381  0.002381   
Document 2  0.003571  0.003571  0.003571  0.003571  0.003571  0.717857   
Document 3  0.003333  0.003333  0.868149  0.003333  0.003333  0.003333   
Document 4  0.096183  0.633519  0.110839  0.004167  0.004167  0.004167   

            Topic 18  Topic 19  
Document 0  0.003846  0.003846  
Document 1  0.002381  0.859524  
Document 2  0.003571  0.003571  
Document 3  0.003333  0.003333  
Document 4  0.004167  0.004167

The following code displays the most likely words for each topic. The resulting pandas table lists the topics as columns, and the contents of each column are words sorted by probability. Thus, the top 3 words of topic 1 are "https", "co", and "rt".

In [27]:
# Function from https://towardsdatascience.com/topic-modeling-quora-questions-with-lda-nmf-aff8dce5e1dd
import numpy as np
def show_topics(vectorizer=vectorizer, lda_model=lda_model, n_words=20):
    keywords = np.array(vectorizer.get_feature_names())
    topic_keywords = []
    for topic_weights in lda_model.components_:
        top_keyword_locs = (-topic_weights).argsort()[:n_words]
        topic_keywords.append(keywords.take(top_keyword_locs))
    return topic_keywords

topic_keywords = show_topics(vectorizer=tweets_vectorizer, lda_model=lda_model, n_words=20)

df_topic_keywords = pd.DataFrame(topic_keywords)
df_topic_keywords.columns = ['Word '+str(i) for i in range(df_topic_keywords.shape[1])]
df_topic_keywords.index = ['Topic '+str(i) for i in range(df_topic_keywords.shape[0])]
df_topic_keywords.T

/srv/conda/envs/notebook/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Topic 0       Topic 1         Topic 2 Topic 3 Topic 4  \
Word 0         like         https           about     the      to   
Word 1          any            co             was      we     you   
Word 2         long            rt       australia      of      it   
Word 3           lt           the  constitutional      in     are   
Word 4   aprilfools            to            left     and      me   
Word 5       thanks            in           study      to      rt   
Word 6       though            is            nice      rt      so   
Word 7          ago            of             one      at      if   
Word 8     watching           for           round   their     the   
Word 9          nsw            on           event     see    that   
Word 10         smh          this       extremist      on      is   
Word 11     tornado            at         talking      re     and   
Word 12         wow           and           piece      so      my   
Word 13          by          with         imagine     his     all   
Word 14      myself           amp         forward      my     can   
Word 15          al  iheartawards         looking    have     but   
Word 16         but   bestfanarmy           weeks    some     one   
Word 17        lose            as          course    that    need   
Word 18       feels           day            lets    life    your   
Word 19   continues            it            2015      be    have   

                 Topic 5   Topic 6    Topic 7 Topic 8     Topic 9    Topic 10  \
Word 0             april     https         10     the        know        game   
Word 1             fools        co        lol    that    turnbull         put   
Word 2              week        to        did     has        call     already   
Word 3             years      what        fun    have     malcolm          20   
Word 4           support        rt         11     for        free         ask   
Word 5             until       out      since      be        will          13   
Word 6            auspol        of         30      of    liberals    adelaide   
Word 7             maybe  activist      bless      he        damn        once   
Word 8           feeling       you       data      in        2014       joins   
Word 9                vs       the         km   first       coles       other   
Word 10            happy   clinton       wind     don       death          dm   
Word 11             gold      this  following   would       major        jack   
Word 12             lmao      with       head      is    cheering       blade   
Word 13               na       her      place   being     shooter     promise   
Word 14           aussie   hillary      doozy      to  suspicious         por   
Word 15            prank        do         12     and       board      sequel   
Word 16    demonstration       and     hahaha    they     keating       robin   
Word 17  turnbullmalcolm       she  education   could        risk  qkbyxyez5c   
Word 18               si        it    weather  strike   obviously      wright   
Word 19        favourite        at       temp     big  ggreenwald      rt_com   

          Topic 11       Topic 12 Topic 13  Topic 14         Topic 15  \
Word 0         not        workers     time        rt         congrats   
Word 1          by       exercise     make        de          welcome   
Word 2      strike          shirt       or     thank             true   
Word 3       going             rt      say        no             talk   
Word 4      tropes          brown     stop      then               24   
Word 5        bury            pro   sydney        en             bird   
Word 6       doesn           link   friday    the100          digital   
Word 7        fuck             by       us        من             lots   
Word 8   beautiful         almost   around       son           assets   
Word 9       photo          click     play    secret               st   
Word 10      those          level     anti        te     